IMGSched/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from schedule import views as user_views
from django.conf.urls import url 

urlpatterns = [
    url('^api/v1/',include('social_django.urls', namespace='social')),
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='schedule/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='schedule/logout.html'), name='logout'),
    path('meeting/',include('schedule.urls'))
]

schedule/urls.py
from django.urls import path, include
from . import views
urlpatterns=[
    path('<int:meeting_id>/add/<int:user_id>/',views.addPartcipant),
    
    path('<int:meeting_id>/',views.detailed_Meeting),
    
    path('new/',views.newMeeting),
    path('',views.allMeeting),
    path('<int:meeting_id>/delete',views.delete_meeting),
    path('<int:meeting_id>/update',views.update_meeting),
]

schedule/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone




class meeting(models.Model):
    creator = models.ForeignKey('auth.User',related_name='creator', on_delete=models.CASCADE)
    time_created = models.DateTimeField(default=timezone.now)
    purpose = models.CharField(max_length=255)
    venue= models.CharField(max_length=255)
    private=models.BooleanField(default=True)
    participants=models.ManyToManyField(User, related_name='participants', through='participant')
    meet_time= models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.purpose

class participant(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    meeting=models.ForeignKey(meeting,on_delete=models.CASCADE)
    joined=models.BooleanField(default=False)

class comment(models.Model):
    user=models.ForeignKey(User,on_delete=models.PROTECT, default=0)
    meeting=models.ForeignKey(meeting, on_delete=models.CASCADE)
    time=models.DateTimeField(default=timezone.now)
    Comment=models.TextField()
    def __str__(self):
        return self.Comment

schedule/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import meeting,comment, participant
import datetime

class UserRegisterForm(UserCreationForm):
    email=forms.EmailField()
    first_name= forms.CharField(max_length=255)
    last_name = forms.CharField(max_length=255)
    class Meta:
        model=User
        fields=['username','email','password1','password2','first_name','last_name']
        
class meetingForm(forms.ModelForm):
    purpose = forms.CharField(label='purpose', max_length=255)
    venue= forms.CharField(label='venue', max_length=255)
    meet_time= forms.DateTimeField(initial=datetime.date.today)
    private = forms.BooleanField(required=False)
    class Meta:
        model= meeting
        fields=['purpose','venue','meet_time','private']

class commentForm(forms.ModelForm):
    Comment = forms.CharField(label='Comment', widget=forms.Textarea)
    class Meta:
        model= comment
        fields=['Comment']

schedule/views.py
from __future__ import print_function
import datetime
import pickle
import os.path
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
from django.shortcuts import render, redirect
from rest_framework import permissions, status
from django.contrib.auth.decorators import login_required
from rest_framework.decorators import api_view, permission_classes
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from rest_framework.parsers import JSONParser
from django.views.decorators.csrf import csrf_exempt
from .serializers import MeetingSerializer, CommentSerializer
from .forms import UserRegisterForm, meetingForm
from .models import meeting, comment, participant
from django.contrib.auth.models import User
import requests
from schedule.permissions import show_meeting, add_invite, show_invite_list
from django.shortcuts import render
from django.utils.safestring import mark_safe
import json
import datetime
from datetime import datetime
from datetime import timedelta

SCOPES = ['https://www.googleapis.com/auth/calendar']

# Create your views here.
def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse("<h1>Your form was saved</h1>")
            
    form = UserRegisterForm()
    return render(request, 'schedule/register.html',{'form':form})

@csrf_exempt
@login_required
def newMeeting(request):
        if request.method == 'POST':
                form1=meetingForm(request.POST)
                form1.instance.creator = request.user
                if form1.is_valid():
                        form1.save()
                        meet_time=request.POST.get("meet_time")
                       
                        meet_time=meet_time.replace(" ","T")
                       
                        
                        
                        service = build_service()
                        event = {
                          'summary': request.POST.get("purpose"),
                          'location': request.POST.get("venue"),
                          'start': {
                            'dateTime': meet_time,
                            'timeZone': 'Asia/Kolkata',
                            
                          },
                          'end': {
                            'dateTime': meet_time,
                            'timeZone': 'Asia/Kolkata',
                            
                          },
                          
                          'reminders': {
                            'useDefault': False,
                            'overrides': [
                              {'method': 'email', 'minutes': 24 * 60},
                              {'method': 'popup', 'minutes': 10},
                            ],
                          },
                        }

                        event = service.events().insert(calendarId='primary', body=event).execute()
                        



                        return redirect('/meeting/')
                else:
                        return HttpResponse("fill form correctly")
        else:
                form = meetingForm()
                return render(request, 'schedule/new.html',{'form':form})
    
@login_required
def allMeeting(request):
        
        meetings1 = meeting.objects.order_by('time_created')
        meetings2 = []
        for meet in meetings1:
                if show_meeting(request,meet):
                        meetings2.append(meet)
        return render(request, 'schedule/all.html', {'meetings': meetings2, 'request':request})

@login_required
def detailed_Meeting(request, meeting_id):

        invited=[]
        to_invite=[] 
        meet=meeting.objects.get(pk=meeting_id)
        to_invite=User.objects.order_by('id')
        spec_users = participant.objects.filter(meeting_id=meeting_id)
        for spec_user in spec_users:
        
                        invited.append(User.objects.get(pk=spec_user.user_id))
        to_invite = list(set(to_invite) - set(invited))
        if show_invite_list(request, meet) != True:
                to_invite=[]
        
        comments1=comment.objects.filter(meeting=meet)
        if show_meeting(request, meet):
                return render(request, 'schedule/details.html',{'meet':meet,'invited':invited, 'to_invite':to_invite,'comments':comments1, 'users':User, 'room_name_json': mark_safe(json.dumps(meeting_id))}) 
        else:
                return HttpResponse("Not accecible to you")
                
@login_required
def addPartcipant(request, meeting_id, user_id):
        
        meet=meeting.objects.get(pk=meeting_id)
        user1=User.objects.get(pk=user_id)
        if add_invite(request, meet, user1):
                
                p1=participant(meeting=meet , user=user1)
                p1.save()
        return redirect("/meeting/")

@login_required
def delete_meeting(request, meeting_id):
        meet=meeting.objects.get(pk=meeting_id)
        if show_invite_list(request, meet ):
                meet.delete()
                return redirect("/meeting/")
        else:
                return HttpResponse("This meeting cant be deleted")

@login_required
def update_meeting(request, meeting_id):
        meet=meeting.objects.get(pk=meeting_id)
        
        now=meet.meet_time
        now=now-timedelta(hours=10)    
        now1 = now.strftime("%Y-%m-%d (%H:%M:%S.%f)")
        
        now1=now1[0:10]+"T"+now1[12:26]+'Z'
        print(now1)
        
        if request.method=='POST':
                service=build_service()
                events_result = service.events().list(calendarId='primary', timeMin=now1,
                                        maxResults=1, singleEvents=True,
                                        orderBy='startTime').execute()
                events = events_result.get('items', [])
                if not events:
                        print('No upcoming events found.')
                for event in events:
                        print(type(event))
                        print(event['summary'])
                        meet.purpose=request.POST.get("purpose")
                        meet.venue=request.POST.get("venue")
                        meet.meet_time = request.POST.get("meet_time")
                        meet.private = request.POST.get("private")
                        meet.save()
                        id1=event['id']
                        event['summary'] = meet.purpose
                        event['location'] = meet.venue
                        time1=meet.meet_time
                        event['start']['datetime'] = time1
                        event['end']['datetime'] = time1
                        updated_event = service.events().update(calendarId='primary', eventId=id1, body=event).execute()
                        print(updated_event['updated'])
                return redirect("/meeting/")


        return render(request, 'schedule/update.html',{'meeting':meet})

def build_service():
        creds=None
        if os.path.exists('token.pickle'):
                with open('token.pickle', 'rb') as token:
                        creds = pickle.load(token)
        if not creds or not creds.valid:
                if creds and creds.expired and creds.refresh_token:
                        creds.refresh(Request())
                else:
                        flow = InstalledAppFlow.from_client_secrets_file(
                                'credentials.json', SCOPES)
                        creds = flow.run_local_server()
        
                with open('token.pickle', 'wb') as token:
                        pickle.dump(creds, token)

        service = build('calendar', 'v3', credentials=creds)
        return service

schedule/templates/schedule/all.html
<h1> {{ user.username }} </h1>
{% if meetings %}
    <ul>
    
    {% for meeting in meetings %}
        
            <li><a href="/meeting/{{ meeting.id }}/">
                <p>Purpose:{{ meeting.purpose }}</p>
                <p>Created by {{meeting.creator}}</p>
                <p>At {{meeting.meet_time}}</p>
            </a></li>
        
    {% endfor %}
    </ul>
{% else %}
    <p>No meetings are available.</p>
{% endif %} 

schedule/templates/schedule/details.html
<h2><p>{{meet.purpose}}</p></h2>
<p>Created by: {{meet.creator}}</p>
<p>at {{meet.time_created}}</p>
<p>The meeting is {{meet.meet_time}}</p>
<a href="/meeting/{{meet.id}}/delete"><button>Delete meeting</button></a>
<a href="/meeting/{{meet.id}}/update"><button>Update meeting</button></a>
{% if to_invite %}
<p>Click to invite more people</p>
    <ul>
    {% for user in to_invite %}
        {% if  user != meet.creator %}
            
        <li>
            <a href='/meeting/{{meet.id}}/add/{{user.id}}'>{{ user.username }}</a>
            
        </li>
        {% endif %}
    {% endfor %}
    </ul>
{% endif %} 

{% if invited %}
<p>people already invited</p>
    <ul>
    {% for user1 in invited %}
        {% if  user1 != meet.creator %}
            
        <li>
            <p> {{user1.username}} </p>
            
        </li>
        {% endif %}
    {% endfor %}
    </ul>

{% endif %} 

<!-- <form method="POST" action="" >
    {% csrf_token %}
    {{ form.as_p}}
    <div>
        <button type="submit">Add comment</button>
    </div>
</form>-->
<h3>Comments</h3>
{% if comments %}
    <ul>
    {% for comment in comments %}
            
        <li>
                {{ comment.user }} - {{comment.Comment}}
        </li>
    {% endfor %}
    </ul>
{% endif %}  



    <textarea id="chat-log" cols="100" rows="20"></textarea><br/>
    
        <input id="chat-message-input" type="text" size="100" name="com"/><br/>
        <input id="chat-message-submit" type="button" value="Send"/>
    
<script>
    var roomName = {{ room_name_json }};

    var chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/chat/' + roomName + '/');

    chatSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        var message = data['message'];
        document.querySelector('#chat-log').value += (message + '\n');
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
        var messageInputDom = document.querySelector('#chat-message-input');
        var user2="{{user.username}}"
        var message = messageInputDom.value;
        var to_send=JSON.stringify({'message': message})
        chatSocket.send(to_send );

        messageInputDom.value = '';
    };
</script>

schedule/templates/schedule/login.html
<div>
    <form method="POST" action=''>
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log In</legend>
            {{ form }}
        </fieldset>
        <div>
            <button type="submit">Login</button>
        </div>
    </form>
    <div>
        <small>
            Need An Account? <a href="{% url 'register' %}">Sign Up Now</a>
        </small>
    </div>
</div>
<a href={% url 'social:begin' 'google-oauth2' %}>Login with Google</a>

schedule/templates/schedule/logout.html
<h2>You have been logged out</h2>
    <div>
        <small></small>
            <a href="{% url 'login' %}">Log In Again</a>
        </small>
    </div>

schedule/templates/schedule/new.html
<h1>{{ user }}</h1>
<form method="POST" action="" >
    {% csrf_token %}
    {{ form.as_p}}
    <div>
        <button type="submit">Create new meeting</button>
    </div>
</form>

schedule/templates/schedule/register.html
<html>
    <head>
        <title>Register Template</title>
    </head>
    <body>
        <div>
            <form method="POST" action=''>
                {% csrf_token %}
                <fieldset>
                    <legend class="border-bottom mb-4">Join Today</legend>
                    {{ form.as_p }}
                </fieldset>
                <div>
                    <button type="submit">Sign Up</button>
                </div>
            </form>
            <div>
                <small>
                    Have An Account? <a href="{% url 'login' %}">Sign in Now</a>
                </small>
            </div>
        </div>
    </body>
</html>

schedule/templates/schedule/update.html
<h1>{{ user }}</h1>
<form method="POST" action="" >
    {% csrf_token %}
    <p>
        <label for="id_purpose">purpose:</label>
        <input type="text" name="purpose" maxlength="255" required="" id="id_purpose" value="{{meeting.purpose}}">
    </p>
    <p>
        <label for="id_venue">venue:</label>
        <input type="text" name="venue" maxlength="255" required="" id="id_venue" value="{{meeting.venue}}">
    </p>
    <p>
        <label for="id_meet_time">meeting time</label>
        <input type="datetime-local" name="meet_time" maxlength="255" required="" id="id_purpose" required>
    </p>
    <p>
        <label for="id_private">Private:</label>
        <input type="checkbox" name="private" id="id_private" value="{{meeting.private}}">
    </p>

    <div>
        <button type="submit">Update meeting</button>
    </div>
</form>